Update README.md
cawa-93/unplugin-auto-expose pull request #10
Opened 2023-04-08 04:25 UTC by TheAutomaTom

Run spellcheck.

2023-04-08 07:52 UTC, cawa-93 requested changes

2023-04-08 07:52 UTC, cawa-93 commented on README.md
> -// preload.ts
Comments with `//` is ok

2023-04-08 07:52 UTC, cawa-93 commented on README.md
> +/// tsconfig.json`:
Comments in json is not ok

2023-04-09 13:57 UTC, merged

2023-04-09 17:13 UTC, cawa-93 commented
Thanks for checking. And sorry for delay 😔

2023-04-09 19:54 UTC, TheAutomaTom commented
Never a rush.  I hope you have more important things to do!

On Sun, Apr 9, 2023, 12:13 PM Alex Kozack ***@***.***> wrote:

> Thanks for checking. And sorry for delay 😔
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cawa-93/unplugin-auto-expose/pull/10#issuecomment-1501173284>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXESHTQAXENJ2OPJXMK2Z5TXALU3LANCNFSM6AAAAAAWXFY57M>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>