feat: add config for multi preload support
cawa-93/unplugin-auto-expose pull request #11
Opened 2023-04-16 04:13 UTC by ymhrainy

thanks for your awesome work on this plugin that makes renderer code using preload api easier (the traditional way of writing  contextBridge.exposeInMainWorld and adding ts type by hand to Window is really unpleasant)

in our use case, there are some different preload entries for different renderer window, and for some window, we must turn off contextIsolation which makes contextBridge.exposeInMainWorld unavailable. Also in some cases the exposed api is meant to be used by third party developers, so we'd rather the variable name to be just like 'nodeVersions' than '__electron_preload__nodeVersions'

so I added some config options to extend the functionality

1. add virtualModuleMap config for multi preload support
2. add exposeName config option for custom variable name exposes
3. add noContextBridgeEntries config option for contextIsolation option

2023-04-18 09:10 UTC, cawa-93 requested changes

2023-04-18 09:10 UTC, cawa-93 commented on src/types.ts
> +  preloadEntry?: string;
In my opinion, we can drop `preloadEntry` entirely. Just use `virtualModuleMap` to specify one or more modules

2023-04-18 09:10 UTC, cawa-93 commented on src/renderer.ts
> +  Object.entries(virtualModuleMap).forEach(([virtualModuleId, entry]) => {
Pls use `for…of` loop here. 😅

2023-04-18 09:10 UTC, cawa-93 commented on src/renderer.ts
> +  const resolvedIdToPreloadEntry: Record<string, string> = {};
This, probably, may be Maps

2023-04-18 09:10 UTC, cawa-93 commented on src/preload.ts
> +          _options.noContextBridgeEntries.includes(info.name);
Optional chaining?

2023-04-18 09:10 UTC, cawa-93 commented on src/types.ts
Need docs for params here as well. Use JSDoc for it.

2023-04-18 09:10 UTC, cawa-93 commented on README.md
Docs needs to be improved. Totally unclear:
- What params are optional and what not.
- What default values and behavior.
- What `exposeName` actually needed.

2023-04-19 04:28 UTC, ymhrainy commented on src/types.ts
> +  preloadEntry?: string;
Agreed. By the way will the config key just be for example 'entries' be better than 'virtualModuleMap'? I'm not that sure, it maybe feel like more precise.

2023-04-19 04:34 UTC, ymhrainy commented on README.md
My apologize, I'll improve the docs later, these  docs are indeed really primitive

2023-04-19 08:56 UTC, cawa-93 commented on src/types.ts
> +  preloadEntry?: string;
`entries` LGTM

2023-08-19 14:38 UTC, closed without merging